language: bash
services: docker

env:
  - VERSION=5.4 VARIANT=
  - VERSION=5.4 VARIANT=alpine
  - VERSION=5.4 VARIANT=apache
  - VERSION=5.4 VARIANT=fpm
  - VERSION=5.4 VARIANT=fpm/alpine
  - VERSION=5.4 VARIANT=zts
  - VERSION=5.4 VARIANT=zts/alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="php:${VERSION}${VARIANT:+-$VARIANT}"
  - image="${image//'/'/-}"

script:
  - travis_retry docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
